use std::env;
use std::path::PathBuf;
use std::process::Command;

/// Locate the `go` binary, extending PATH with common install locations if needed.
fn find_go() -> String {
    // Try standard PATH first
    if Command::new("go").arg("version").output().is_ok() {
        return "go".to_string();
    }
    // Common non-PATH Go install locations
    let candidates = [
        "/usr/local/go/bin/go",
        "/home/abbas/go-sdk/go/bin/go",
        "/usr/bin/go",
        "/snap/bin/go",
    ];
    for path in candidates {
        if std::path::Path::new(path).exists() {
            return path.to_string();
        }
    }
    panic!("Could not find `go` binary — please install Go and ensure it is on PATH");
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();

    let lib_name = match target_os.as_str() {
        "windows" => "folio.dll",
        "macos" | "darwin" => "libfolio.dylib",
        _ => "libfolio.so",
    };

    let lib_path = out_dir.join(lib_name);
    let go_bin = find_go();

    // Determine Go binary directory so we can set GOROOT / PATH explicitly
    let go_bin_path = PathBuf::from(&go_bin);
    let go_bin_dir = go_bin_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("/usr/local/go/bin"));

    // Build an extended PATH that includes the Go bin directory
    let original_path = env::var("PATH").unwrap_or_default();
    let extended_path = format!("{}:{}", go_bin_dir.display(), original_path);

    // Create a scratch Go module directory inside OUT_DIR for fetching/building folio.
    // We need an explicit go.mod so `go get` and `go build` work in module-aware mode.
    let go_mod_dir = out_dir.join("folio_go_module");
    std::fs::create_dir_all(&go_mod_dir).expect("failed to create go module scratch dir");

    let go_mod_content = "module folio_build\n\ngo 1.21\n";
    std::fs::write(go_mod_dir.join("go.mod"), go_mod_content)
        .expect("failed to write go.mod");

    // go get: fetch the folio module (updates go.mod / go.sum in scratch dir)
    let get_status = Command::new(&go_bin)
        .args(["get", "github.com/carlos7ags/folio/export"])
        .current_dir(&go_mod_dir)
        .env("PATH", &extended_path)
        .env("GOPATH", out_dir.join("gopath").to_str().unwrap())
        .status()
        .expect("Failed to run `go get` — is Go installed?");

    if !get_status.success() {
        // Non-fatal: go get may fail if network is unavailable but module is cached
        eprintln!("cargo:warning=`go get` did not succeed (network may be unavailable); trying cached module");
    }

    // Compile folio Go export package as C-shared library
    let status = Command::new(&go_bin)
        .args([
            "build",
            "-buildmode=c-shared",
            "-o",
            lib_path.to_str().unwrap(),
            "github.com/carlos7ags/folio/export",
        ])
        .current_dir(&go_mod_dir)
        .env("PATH", &extended_path)
        .env("GOPATH", out_dir.join("gopath").to_str().unwrap())
        .status()
        .expect("Failed to run `go build` — is Go installed?");

    assert!(status.success(), "go build -buildmode=c-shared failed");

    // The header is generated by `go build -buildmode=c-shared` with the same basename
    // as the output library but with a `.h` extension.
    // e.g. `-o libfolio.so` → `libfolio.h`
    let lib_stem = lib_name
        .trim_end_matches(".so")
        .trim_end_matches(".dylib")
        .trim_end_matches(".dll");
    let header_path = out_dir.join(format!("{lib_stem}.h"));

    // Generate Rust bindings from the C header produced by cgo
    let bindings = bindgen::Builder::default()
        .header(header_path.to_str().unwrap())
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("Unable to generate bindings from folio.h");

    bindings
        .write_to_file(out_dir.join("bindings.rs"))
        .expect("Couldn't write bindings.rs");

    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=dylib=folio");

    // Embed the OUT_DIR as an rpath so the dynamic linker can find libfolio.so at runtime
    // without requiring LD_LIBRARY_PATH to be set manually.
    println!("cargo:rustc-link-arg=-Wl,-rpath,{}", out_dir.display());
}
